name: flutter_umami
description: Simple Umami Analytics Flutter SDK
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  fk_user_agent: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  solvro_config: ^1.0.1

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
