name: flutter_umami
description: Simple Umami Analytics Flutter SDK
version: 0.3.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  device_user_agent: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  solvro_config: ^1.0.1

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
